
# Code generation of static link, referencing variables which redefines
# outer variables and the calling a function in an outer scope
# The references to the variable 'a' in the inner function 'sub'
# should refer to the 'a' declared in 'b'
# However, when 'sub' calls 'c', the 'a' in 'c' refers to the outer 'a'
var a : int, temp : int;

i = 10;
j = 1;

while i < 20 do {
   while j < 5 do {
    j = j + 1;
    write j;
   }
   i = i + 1;
   write i;
}
